name: manage
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  shared_preferences: ^2.0.15
  intl: ^0.20.2
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.0.11
  google_fonts: ^8.0.0
  http: ^1.1.0
  excel: ^4.0.0
  file_picker: ^8.0.0
  fl_chart: ^0.70.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
    foreground_image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/nf logo.jpg
